Уровень 1 на проверку
stranse/RepPro pull request #1
Opened 2022-04-09 12:29 UTC by stranse

2022-04-09 13:30 UTC, DenVilk requested changes
Преобразовать все классы из файла ```reciept.py``` и ```utils.py``` в поля/атрибуты одного класса ```Reciept```.

2022-04-09 13:30 UTC, DenVilk commented on device.py
> +        self.operation_system = input("Укажите операционную систему: ")
Убрать ввод информации из \_\_str\_\_().

2022-04-09 13:30 UTC, DenVilk commented on device.py
> +        self.diag2 = diag2
Убрать нумерацию у свойства.

2022-04-16 18:50 UTC, stranse commented on device.py
> +        self.diag2 = diag2
Убрал

2022-04-16 18:50 UTC, stranse commented on device.py
> +        self.operation_system = input("Укажите операционную систему: ")
Убрал

2022-04-16 18:52 UTC, stranse commented
Полностью изменил reciept.py

2022-04-16 18:52 UTC, closed without merging